# Header
menu:
  Home: /
  Category: /category
  Archives: /archives
  About: /about
  Link: /link
link:
  Github: //github.com/samsam2310
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
# - tag
- tagcloud
# - archive
- recent_posts


# Miscellaneous
google_analytics: UA-72943167-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
