# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Github: //github.com/samsam2310
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
# - tag
- tagcloud
# - archive
- recent_posts


# Miscellaneous
google_analytics:
favicon: /favicon.ico
disqus_shortname:
twitter:
google_plus:
fb_admins:
fb_app_id:
